### ISSUE TITLE
Use of language in the Conversion document

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-57-to-S-101-conversion-sub-WG#10]
During meeting 6 (29 April 2021) of the Sub-Group, a long discussion took place on the Use of language in the document (must/should/may and other wordings).
It was decided to gather a group of volunteers to work on this topic. This issue has been created so that the discussions be available to the rest of the sub-group.

**Comment by Christian-Shom** [comment]
Dear all,

thanks to Mikus for his mail.

I do agree that the language in the conversion document should not necessarily be the same than in the UOC or DCEG. This does not mean it should be different.

Yet, I don't think this is only a document that advises everyone how the standard transfers and that there is no recommendations needed.
The UOC advises on how to encode real world information in S-57.
The DCEG advises on how to encode real world information in S-101.
The conversion document will exist because conversion will not be 100% straightforward and automatic. If this were the case, I assume there would be no need for a conversion document.

My view is that the document must identify eveywhere data will have to be prepared or mappings (customization of the converters) elaborated (I'm not saying we should explain them in detail, but why not giving examples?) to facilitate the conversion. The guidance will be useful to both HOs and Conversion tools providers.
There are some situations where the data must be prepared. How to have the S-101 feature Discoloured Water created without populating INFORM on the S-57 CTNARE? Then, if the text string encoded in INFORM on the CTNARE must be in the format "Discoloured water" for GB or "Discolored water" for US is another story. But advise must be given. I agree it must be software or script independent.
NOTE: the comments above are more related to 1.1 (general) than 1.3 (Use of language).

As for the Use of language proper, I find the document, as written by Jeff, quite unambiguous.

Happy to talk about all this tomorrow.

Best regards,

Christian

**Comment by MikusRL** [comment]
Thank you for the pre meeting catch-up today on language matters. It is much more clearer now regarding the intended dual help purpose, and Jeff, you got one more supporter of the main ideas of this guideline document. I certainly am for the proposed way forward regarding the section 1.3 language. And Cristian, it of course was not purely thinking of what converters must do, but thinking of HOs, if they know what converters are definitely requested to do, then it would be easier to discuss with the converter developer on how to handle data that is not described in this document and needs to be discussed. It is clear now, that with the Must Should and May, this document will try to facilitate and advice on way forward for that bit as well.
One last consideration though regarding the word "automatically". It is used in most cases with the term "will be populated" or "will be converted". I believe this states that it is "without an intervention", but that is I assume very subjective from converter to converter. Unless you Jeff had a specific idea behind this word from IHO perspective, meaning ....something in particular, I suggest that the "will be converted" or  "will be populated" is enough and inclusive of automatic, semiautomatic, with some user input or customization in beforehand, or manually QC features as they are transferred one by one, etc. As long as the definition of use "will" in section 1.3 elaborates that perhaps as well. This consideration comes from the experiences in different projects in HOs, that HO can assume that if particular converter is stated as this guidance compatible, might end up not the same as HO think the automatic means for them. Just thinking of that part on you Jeff as a "call center" again.

**Comment by Christian-Shom** [comment]
Language conventions have been agreed and applied.
Please open a new issue if needed.
